[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
fern = "0.5"
chrono = "0.4"
anyhow = "1"
boa_engine = "0.18.0"
dom = { path = "../dom" }
serde = { version = "1.0.202", features = ["derive"] }
boa_gc = "0.18.0"
once_cell = "1.19.0"
